### ISSUE TITLE
How to apply usbs on other SDPs?

### ISSUE THREAD

**Issue by luotuoqingshan** [rangell/specbm#2]
Dear Rico Angell,

Thanks for the great work! The paper is exciting and the code is well-organized.

I may miss something, but how can I test USBS on other SDPs?

The SDP problem looks to be read from a mat file, can you provide more explanation about it?

Kind Regards,
Yufan

**Comment by rangell** [comment]
The SDP problem data (`sdp_state`) is specified in a namedtuple,`SDPState` in `utils/common.py`, of tensors. The mat file provides some of the problem data (e.g. a sparse graph for the MaxCut problem), but this data needs to be transformed and augmented into an `SDPState` instance. For example, take a look at the `initialize_state` function in `utils/maxcut_helpers.py`. In order to use USBS on other SDPs you need to implement this function to construct the state. 

Documentation for the structure of these tensors is in progress, but for now it should be relatively straightforward to infer the structure of the examples. Please let me know if you have any questions about the structure of the SDP state tensors.

Additionally, it is very important that you include the following line at the beginning of your main function
`jax.config.update("jax_enable_x64", True)`

**Comment by luotuoqingshan** [comment]
Thanks for the instructions!
